from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
MODEL_PATH = PROJECT_ROOT / "models" / "model.tflite"
DB_PATH = PROJECT_ROOT / "data" / "detections.db"
LOG_DIR = PROJECT_ROOT / "logs"

CLASSES = ["Aedes", "Culex", "No_Mosquito"]
CONFIDENCE_THRESHOLD = 0.72
INPUT_SIZE = (224, 224)
NO_MOSQUITO_CLASS_IDX = 2
MIN_MOSQUITO_CONFIDENCE_MARGIN = 0.15

PI_CAMERA_INDEX = 0
PI_CAMERA_WIDTH = 640
PI_CAMERA_HEIGHT = 480
PI_CAMERA_TARGET_FPS = 10

TARGET_LATENCY_MS = 100
MAX_LATENCY_MS = 150

OLED_ENABLED = True
OLED_ADDRESS = 0x3C
OLED_WIDTH = 128
OLED_HEIGHT = 64

DB_ENABLED = True
UPDATE_INTERVAL = 1.0
MIN_DETECTION_INTERVAL = 3.0

LOG_LEVEL = "INFO"

DASHBOARD_ENABLED = True
DASHBOARD_HOST = "0.0.0.0"
DASHBOARD_PORT = 5000

